name: On Push
on:
  push:
    branches:
      - main
      - staging
      - dev   

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tflint:
    name: tflint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4.2.2

    - name: Cache plugin dir
      uses: actions/cache@v4.2.3
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4.1.1

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f sarif

  trivy:
    name: trivy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.31.0
      with:
        scan-type: 'config'
        hide-progress: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    - name: Upload all scan results as a SARIF zip package
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: iac-scan-results
        path: ./*.sarif
        retention-days: 30